<?php

namespace fortuneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository {

    protected $name = "email"; //short name used for the query

    /**
     * Find all quotes by date inversed
     * 
     * @return  object
     */

    public function myFindAllEmails() {
        // prepare the query
        $q = $this->createQueryBuilder($this->name)
                ->select($this->name . ".email")
                ->where($this->name .".active = true")
        ;
    
        return $q->getQuery()->getArrayResult();
    }

}
